### PR TITLE
Fix inneficiency when output is full

### PR DESCRIPTION
**Pull request by MattMcMullan**
Check to see if we can actually put stuff into the output inventory
before checking each tree.

There are two potential ways to remove the hard-coded value.  First, we
could look up the max amount that can drop from a tree at runtime and
put it there.  Alternatively, we could allow the output stack to go over
max if it was under max before we tried to add stuff to it.  This is
already done in some places for the vanilla game.

### CODE REVIEW

**Comment by StephenWard** [comment]
[Edit]
fixed by (duplicate of) https://github.com/Blu3wolf/Treefarm-Lite/pull/32

[Edit]
Matt - in terms of the fix, game.item_prototypes[] is excruciatingly slow so the access would definitely have to be cached

**Comment by Blu3wolf** [comment]
I considered #32 a good short term fix. As noted there, its still got room for further improvement. Whether this represent further improvement Im not sure. This also looks like it leaves the unharvestable checks in place? Seems like that would slow things down a little. 

Its never a good idea to make judgement about performance by just reading code though. What was the actual performance improvement this patch makes?

**Comment by StephenWard** [comment]
@Blu3wolf #32 is a pretty decent fix, since it took UPS from 11 to 57 . There's no substitute for measuring performance, but I would also expect #32 to perform better than this one when farms are backed up, simply because this one checks inventory for space once, and then runs through all 60 trees on the farm, whereas #32 will harvest max 10 trees (10 x 5 wood = 50) and then stop after harvesting the 11th one fails.

**Comment by MattMcMullan** [comment]
See the commit message for details, but it looks like alone, the patches had comparable performance. With StephenWard's suggestion of caching stack sizes, the performance of this solution becomes drastically better, but is further improved by using both changes in tandem.

**Comment by Blu3wolf** [comment]
Alright, Im going to need to see some numbers then. Ive not got any time really to play with this in the next week or so, so if there's not a set of numbers for the performance improvement by the end of next week, Ill look at it then.

**Comment by MattMcMullan** [comment]
"On a test map with 31 full farms, I couldn't get the UPS to drop below
60.  Before this change, it was hovering between 1.5-2.5 ms spent in
this mod. After this change, it was hovering around 0.15-0.2 ms, with
occasional spikes up to 0.5 ms.
When using only Matrix0150's change on the same save, I get 1.25-2.25 ms
spent in TF.  When combining this change with Matrix0150's change, it
drops to 0.125-0.2 on average with spikes at 0.25.
This patch to my change is certainly the fastest performing fix for this
performance problem, but it appears to smoothed out by Matrix0150's
change, so combining them would be ideal." - The detailed commit message from the "Cashe the known stack sizes" change

**Pull request merged**
