### PR TITLE
Fixes for latest factorio

### PR DESCRIPTION
**Pull request by dreadicon**
The fix was pretty simple, even if it alters how the Field is selected. I just applied the changes and tested them briefly; everything seems to work fine. Also iterated to next minor version of mod to help differentiate.

### CODE REVIEW

**Comment by marvinside** [comment]
These fixes make the Mod work for 14.21, however there are 2 bugs that seem to be caused by DyTech.

1. If you plant Germlings and mine them, you have another Item in your Inventory (also a Germling) that can not be placed nor can be placed by a treefarm.
 The Bugged Germling belongs to the mod DyTech then.

2. I found myself with 2 different Treefarm MK1 items in my inventory, looks like the same as 1, but they are usable.

**Comment by dreadicon** [comment]
That sounds like a bug in Dytech, but I can't say as I haven't used Dytech in years. Wasn't meant as something as grand as a complete and perfect fix, just sufficient for most players. I don't have much time these days or I'd investigate further. As it is, this fix still hasn't been merged, so I'm considering posting a temporary thread for the mod till Blu3wolf returns.

**Comment by Blu3wolf** [comment]
Please feel free to. Im around to comment here, but I haven't worked on Treefarm in quite some time, which was part of the reason I added a collaborator to the repository - so that someone else could approve PRs in my absence. That doesn't seem to have worked, though.

**Comment by Blu3wolf** [comment]
Id generally prefer as a style thing that PRs not be made to master branch, but develop. That way, master can remain at the last stable version for a factorio version, with develop containg changes up to a prerelease state.

**Comment by dreadicon** [comment]
Oh, hey Blu3! sure, I can make a PR for dev rather than Master. Just didn't know what pattern you were using. There's more than a few ways to use Git. I'll go set that up now.

**Comment by Blu3wolf** [comment]
Yeah, if i was going to be maintaining it I would probably add a CONTRIBUTING.md to the repo, with notes on that sort of thing.

**Pull request closed without merging**
