### PR TITLE
Fix mk2 crash when built

### PR DESCRIPTION
**Pull request by Blu3wolf**
Just going to merge these into develop first up @matepeter90, instead of master branch.

### CODE REVIEW

**Comment by Blu3wolf** [comment]
7804b57 reverts the line removal, correcting the argument.

**Comment by matepeter90** [comment]
Thanks, next time I will create the pull request for the development branch.

**Comment by Blu3wolf** [comment]
Yeah, the idea was that the only commits to master are releases, but FF merges have happened all over the place. What I really need to start doing is squash commits to master, and FF merges everywhere else.

Thanks for the PR though, saved me quite some time having to debug that error!

**Comment by matepeter90** [comment]
No problem, I played with the fix for some hours and the trees were growing nicely.

**Pull request merged**
