### PR TITLE
Feature/performance

### PR DESCRIPTION
**Pull request by StephenWard**
rewrote treefarm code based on the work @Rseding91 did
includes all the performance work I posted on the initial issue request as well
so... 2500 mk2 farms are easily supported. support for mk1s is harder to measure but will be comparable

I updated the TreeFarm version to 4.0 and tested upgrading from v3.7 to v4.0 - which works
I also tested w/ latest versions of Treefarm-AC, Treefarm-Caffiene, and Treefarm-AlienPlant, all of which work for both upgraded saves and new games. I have not tested dytec or any other mods that add plants. I also took a look through the bug history and tested this new version for those bugs, fixing the ones I found.

All uses of the Surface and Force are correct - no hardcoded references to "nauvis" or game.forces.player

notes
- game.item_prototypes[] is slow (so its not used)
- lots of outstanding deconstruction requests will severely degrade performance

### CODE REVIEW

**Comment by StephenWard** [comment]
note: this also correctly handles the "minable_properties" field on EntityPrototype when harvesting plants, so fixing the issue raised https://forums.factorio.com/viewtopic.php?f=44&t=23417 is just a matter of increasing the number of output slots in the mk1 farm prototype

**Comment by Blu3wolf** [comment]
> lots of outstanding deconstruction requests will severely degrade performance

How severely? Im going to look over the control.lua file (Github wont display it, too many changes). Normally a push to master is for a full release, so you reckon this is good to go as 0.4.0?

**Comment by StephenWard** [comment]
With 2500 farms, if you destroy the tree outright w/ entity.destroy() instead of calling entity.order_deconstruction(), it will run around 7-15 and 60FPS with a stutter every now and then.
If you order_deconstruction() then it will run at 90+ and < 25 FPS (assuming no one ever harvests the trees)

I've done a full upgrade and regression test, so I think it's good for 0.4.0, but since you're responsible for the releases I would get the code from my repo and run some tests on it first to make sure I'm not lying/crazy/seeing things.

**Comment by StephenWard** [comment]
also, if, for tracking the releases better, you need me to make this a pull request into a different branch, just let me know

**Comment by Rseding91** [comment]
That performance with deconstructing is not related to the mod but just the internals of Factorio and deconstructing trees at massive numbers and not dealing with them. Don't worry about that.

**Comment by StephenWard** [comment]
@Rseding91 I know. It's just really, really annoying... since it's the only thing preventing me from testing 10,000 farms :)

**Comment by secondadvent** [comment]
Testing this out, I had run into a problem where the field kept planting germlings even after the field was already full, but they didn't seem to be appearing anywhere. After removing the field and the germlings, I realized they were stacking on top of each other, and it turns out it's because I use squeak through (with trees set to have no collision). Manually adjusting squeak through to set the minimum collision size 0.01 instead of 0 fixed the fields while keeping a minimal collision box.

Wanted to let you know about the collision box planting issue since I'm sure I'm not the only one who adjusts tree collision boxes, and it's pretty confusing to see the fields using up more germlings than they should. Haven't tested on the official versions to see if it happens there as well.

**Comment by StephenWard** [comment]
it will happen on the official versions as well, since both check to see if they can place a germling the same way. still, it's an interesting bug to try and fix

**Comment by Rseding91** [comment]
@StephenWard sounds like "not a bug" and not worth trying to "fix" - better to spend time on other things.

**Comment by Blu3wolf** [comment]
@StephenWard just for future stuff mebbe make the PR to develop instead of master. Seeing as Im still getting the hang of Git its not such a big deal anyway.

**Pull request merged**
